### ISSUE TITLE
Trying to install - Building wheel for lxml (pyproject.toml) ... error

### ISSUE THREAD

**Issue by eXpressionist** [sinedie/SRTranslator#69] opened 2023-10-18 20:24 UTC
W10 x64, Python 3.12.
I've installed Microsoft C++ Build Tools with "C++ build tools".
Then trying to install SRTranslator via pip  and getting error

```
<...>
Building wheel for lxml (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for lxml (pyproject.toml) did not run successfully.
  │ exit code: 1

<...>

 C:\Users\EXPRES~1\AppData\Local\Temp\xmlXPathInittcl7bd0n.c(1): fatal error C1083: cannot open include file: libxml/xpath.h: No such file or directory,
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      *********************************************************************************
```

I've installed lxml via pip, and also did pip install --upgrade setuptools - doesn't help :(
Tried to manually install from www.lfd.uci.edu lxml-4.9.0-cp311-cp311-win_amd64.whl and lxml-4.9.0-cp311-cp311-win32.whl - both are "not a supported wheel on this platform".

**Comment by sinedie** [comment] 2023-10-18 21:06
Seems like lxml library isn't available in python 3.12 (yet). Try downgrade python (3.10 maybe???) or ask the developers of that package.

Closing it due the issue is not from this package

**Closed by sinedie** 2023-10-18 21:06 UTC

**Comment by eXpressionist** [comment] 2023-10-18 21:43
Just please change libxml==4.9.**3** (actual version) in requirements and it should work.

**Comment by sinedie** [comment] 2023-10-20 03:27
@eXpressionist done
