### ISSUE TITLE
Error srtranslator

### ISSUE THREAD

**Issue by funmolde** [sinedie/SRTranslator#98] opened 2024-11-11 14:40 UTC
Hello Please fix the error , Thank You -_- 
Windows 11 64 bit
Python 3.9
CMD :
python -m srtranslator -i en -o fr input.srt

Loading input.srt
Backup file found = input.srt.tmp
Starting from subtitle 0
... Translating 0 %
Timed out trying to get element (XPATH = //button[@data-testid='translator-lang-option-en'] | //button[text()='English'])
Saving C:\Users\Max\Documents\input.srt.tmp
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python39\lib\site-packages\srtranslator\translators\selenium_utils.py", line 89, in __init__
    self.element = find_element(*locator)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\Max\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@data-testid='translator-lang-option-en'] | //button[text()='English']
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python39\lib\site-packages\srtranslator\__main__.py", line 113, in <module>
    srt.translate(translator, args.src_lang, args.dest_lang)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python39\lib\site-packages\srtranslator\srt_file.py", line 181, in translate
    translation = translator.translate(
  File "C:\Users\Max\AppData\Local\Programs\Python\Python39\lib\site-packages\srtranslator\translators\deepl_scrap.py", line 135, in translate
    self._set_source_language(source_language)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python39\lib\site-packages\srtranslator\translators\deepl_scrap.py", line 104, in _set_source_language
    self._set_language(language, "//*[@data-testid='translator-source-lang']")
  File "C:\Users\Max\AppData\Local\Programs\Python\Python39\lib\site-packages\srtranslator\translators\deepl_scrap.py", line 123, in _set_language
    Button(self.driver, "XPATH", xpath).click()
  File "C:\Users\Max\AppData\Local\Programs\Python\Python39\lib\site-packages\srtranslator\translators\selenium_utils.py", line 98, in __init__
    sys.exit()
SystemExit
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection. HTTPConnection object at 0x00000171A0ECC640>: Failed to establish a new connection: [WinError 10061] No connection could be established because the target computer expressly refused it')': /session/f2eedae8-edfe-4b40-9f5e-cb60e0d714a1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection. HTTPConnection object at 0x00000171A0ECC550>: Failed to establish a new connection: [WinError 10061] No connection could be established because the target computer expressly refused it')': /session/f2eedae8-edfe-4b40-9f5e-cb60e0d714a1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection. HTTPConnection object at 0x00000171A0F87250>: Failed to establish a new connection: [WinError 10061] No connection could be established because the target computer expressly refused it')': /session/f2eedae8-edfe-4b40-9f5e-cb60e0d714a1

**Comment by sinedie** [comment] 2024-11-11 15:53
Hey there, can't reproduce it... Maybe it is a network issue? try showing the browser so you can see if the page is actually loading

`python -m srtranslator -i en -o fr input.srt -s`

**Comment by funmolde** [comment] 2024-11-11 16:20
> python -m srtranslator -i en -o fr input.srt -s
here is a video when I launch the command
It worked for 3 days and today it doesn't work anymore.

Thank you 

Uploading 20241111_171340.mp4…

**Comment by funmolde** [comment] 2024-11-11 16:22
> Hey there, can't reproduce it... Maybe it is a network issue? try showing the browser so you can see if the page is actually loading
> 
> `python -m srtranslator -i en -o fr input.srt -s`

here is a video when I launch the command
It worked for 3 days and today it doesn't work anymore.

Thank you 

Uploading 20241111_171340.mp4…

**Comment by sinedie** [comment] 2024-11-11 16:27
you didn't upload the video....

**Comment by funmolde** [comment] 2024-11-11 16:41
> you didn't upload the video...
Sorry
streamable.com/7ginq3

**Comment by sinedie** [comment] 2024-11-11 17:00
The only difference I can notice is the banner down the screen. Maybe try to close it before it fail. I tried to replicate it going to deepl french site but the banner won't appear to me.

Also you could check the others translators, deepl is the default but there are more, check the docs.

Also, if you go to https://deepl.com/en/translator does the banner appears to you?

**Comment by funmolde** [comment] 2024-11-11 17:12
> The only difference I can notice is the banner down the screen. Maybe try to close it before it fail. I tried to replicate it going to deepl french site but the banner won't appear to me.La seule différence que je peux remarquer est la bannière en bas de l'écran. Essayez peut-être de le fermer avant qu'il échoue. J'ai essayé de le reproduire sur le site français profond mais la bannière ne m'apparaît pas.
> 
> Also you could check the others translators, deepl is the default but there are more, check the docs.Vous pouvez également vérifier les autres traducteurs, deepl est la valeur par défaut mais il y en a d'autres, consultez la documentation.
> 
> Also, if you go to https://deepl.com/en/translator does the banner appears to you?De plus, si vous allez sur [https://deepl.com/en/translator,](https://deepl.com/en/translator) la bannière vous apparaît-elle ?

No, even in private browsing I don't have it the banner appears

**Closed as completed** 2024-11-22 23:15 UTC
