### ISSUE TITLE
No translators working

### ISSUE THREAD

**Issue by jaum20** [sinedie/SRTranslator#87] opened 2024-04-22 20:40 UTC
with `TranslatePy`:

```
... Translating 0 %
C:\Users\user\AppData\Roaming\Python\Python312\site-packages\urllib3\connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.reverso.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Roaming\Python\Python312\site-packages\srtranslator\srt_file.py", line 188, in translate
    subs_slice[i].content = translation[i]
                            ~~~~~~~~~~~^^^
IndexError: list index out of range
```

With `PyDeepLX`

python crashes

With `DeeplTranslator`

```
... Translating 0 %
Timed out trying to get element (XPATH = //button[@data-testid='translator-lang-option-pt'] | //button[text()='Portuguese'])
```

Package (0.3.6.) installed using `pip `

**Comment by sinedie** [comment] 2024-04-25 14:47
Can't reproduce, can you share the .srt file? tested `Translatepy` and `DeeplTranslator`. Both are working normally

**Comment by jaum20** [comment] 2024-04-25 15:35
I tried on linux and it's working. Maybe the problem is related to windows

**Comment by sinedie** [comment] 2024-07-16 13:44
Closing it as I couldn't reproduce (not even on windows). Feel free to reopen if issue keeps happening

**Closed by sinedie** 2024-07-16 13:44 UTC
