### ISSUE TITLE
New GUI Version not opening giving error 

### ISSUE THREAD

**Issue by h4rdkor1** [sinedie/SRTranslator#85] opened 2024-02-05 17:05 UTC
Hi @sinedie Thank you for creating the GUI version for all of us. I am getting error when trying to run the new GUI version of the translator but its not working. I am getting the below error.

`Traceback (most recent call last):
  File "\app\srtranslatorGUI\__main__.py", line 1, in <module>
    from srtranslatorGUI.app import main
  File "\app\srtranslatorGUI\app.py", line 3, in <module>
    import toga
ModuleNotFoundError: No module named 'toga'
`
![image](https://github.com/sinedie/SRTranslator/assets/21197676/d6f392ea-9662-42b7-91d6-d7d7a76fd623)

**Comment by sinedie** [comment] 2024-02-05 17:08
Windows user? let me check

**Comment by sinedie** [comment] 2024-02-05 17:43
Last release .msi updated. Close if issue solved

**Comment by h4rdkor1** [comment] 2024-02-05 17:52
Still not working giving the same error. Does this program require something to be preinstalled in order to work.

![image](https://github.com/sinedie/SRTranslator/assets/21197676/1b76bc12-3cc0-44f7-99f8-57103baeb6b3)

**Comment by sinedie** [comment] 2024-02-05 20:13
The build process on windows is failing when adding app requirements. Right now I don't have the time to fix it, while I manage to fix it, try [this](https://github.com/sinedie/SRTranslator?tab=readme-ov-file#usage-from-gui) steps to generate your own .msi file.

**Comment by h4rdkor1** [comment] 2024-02-08 06:29
Hi @sinedie, I tried to do what you said but I don't have much knowledge about phyton so cant get anywhere. If you get time to fix this I will be really grateful Thank you.

**Comment by merida77** [comment] 2024-02-08 08:04
Hi @sinedie. I don't know too. I am patiently waiting for you to hopefully solve it.

**Comment by arlovibre** [comment] 2024-02-08 08:11
Hi @sinedie. I love your work. It would be awesome if you had the time to fix this. Best wishes to you, and keep up the good work! :)

**Comment by k-aito** [comment] 2024-02-16 10:53
Hello @merida77 @arlovibre @h4rdkor1 

I tried to add "toga" to the windows requires can you give it a try, I cannot try it myself because I don't have a windows.

[master-windows-2022.msi.zip](https://github.com/sinedie/SRTranslator/files/14310016/master-windows-2022.msi.zip)

**Comment by arlovibre** [comment] 2024-02-16 11:02
There is an error again, the same one.

![image](https://github.com/sinedie/SRTranslator/assets/141356815/00582657-cd89-4fdc-bdc8-faa8c16cbbd5)


> Hello @merida77 @arlovibre @h4rdkor1
> 
> I tried to add "toga" to the windows requires can you give it a try, I cannot try it myself because I don't have a windows.
> 
> [master-windows-2022.msi.zip](https://github.com/sinedie/SRTranslator/files/14310016/master-windows-2022.msi.zip)

**Comment by h4rdkor1** [comment] 2024-02-16 11:36
Hi @k-aito , Thank you for trying to fix the issue but I am still getting the same error as before.

**Comment by m1nuzz** [comment] 2024-02-16 16:29
> Hi @k-aito , Thank you for trying to fix the issue but I am still getting the same error as before.

same:(

**Comment by k-aito** [comment] 2024-02-16 17:45
I don't have any idea...

Each I tried to add the requirement in the windows section, but normally by default they each get another GUI dependence, and it would normally bring back toga with him.

Without having windows to build or test, it's very hard.

The best would that someone with Windows and python knowledge try to follow https://github.com/sinedie/SRTranslator?tab=readme-ov-file#usage-from-gui like suggested @sinedie

**Comment by k-aito** [comment] 2024-02-18 02:30
Hello @merida77 @arlovibre @h4rdkor1

I dig a bit more and I noticed an issue https://github.com/beeware/briefcase/issues/977

It looks like the linked commit is in toga 4.2 so I rebuild the 2 msi with toga 0.4.1 and toga 0.4.2 (you can see it in the zip name).

It looks like 0.4.2 has an issue with linux so I hope that 0.4.1 would be enough but we will see.

[fix-import-toga-error-windows-2022-0.4.1.msi.zip](https://github.com/sinedie/SRTranslator/files/14320887/fix-import-toga-error-windows-2022-0.4.1.msi.zip)

[fix-import-toga-error-windows-2022-0.4.2.msi.zip](https://github.com/sinedie/SRTranslator/files/14320888/fix-import-toga-error-windows-2022-0.4.2.msi.zip)

**Comment by h4rdkor1** [comment] 2024-02-18 08:45
Hi @k-aito, I tried both versions and both gave me the same toga error.

**Comment by arlovibre** [comment] 2024-02-18 09:11
> Hello @merida77 @arlovibre @h4rdkor1
> 
> I dig a bit more and I noticed an issue [beeware/briefcase#977](https://github.com/beeware/briefcase/issues/977)
> 
> It looks like the linked commit is in toga 4.2 so I rebuild the 2 msi with toga 0.4.1 and toga 0.4.2 (you can see it in the zip name).
> 
> It looks like 0.4.2 has an issue with linux so I hope that 0.4.1 would be enough but we will see.
> 
> [fix-import-toga-error-windows-2022-0.4.1.msi.zip](https://github.com/sinedie/SRTranslator/files/14320887/fix-import-toga-error-windows-2022-0.4.1.msi.zip)
> 
> [fix-import-toga-error-windows-2022-0.4.2.msi.zip](https://github.com/sinedie/SRTranslator/files/14320888/fix-import-toga-error-windows-2022-0.4.2.msi.zip)

Hello @k-aito. Thank you for trying again, I tried both versions and got the same "toga" error again.

**Comment by k-aito** [comment] 2024-02-18 09:37
Hello @merida77 @arlovibre @h4rdkor1

Sorry pinging everyone again, I tried one more time this time by using the workaround of the issue.

Using the version defined in the original file but adding `toga-core` in each section.
Let's hope it's the right one

[fix-import-toga-error-windows-2022.msi.zip](https://github.com/sinedie/SRTranslator/files/14321895/fix-import-toga-error-windows-2022.msi.zip)

**Comment by arlovibre** [comment] 2024-02-18 09:52
Thank you for trying again @k-aito, but again, the same error.

![image](https://github.com/sinedie/SRTranslator/assets/141356815/03ad228b-5b02-457b-b8e9-43941ec8f1f7)

**Comment by k-aito** [comment] 2024-02-18 10:17
I have no more ideas for now sadly. It would be interesting to see if the normal briefcase process is working properly on Windows.

It would let us test it is related to briefcase directly or the packaging of briefcase but there is a need of a Windows computer for trying that sadly.

**Comment by k-aito** [comment] 2024-02-18 20:50
I think I have something @sinedie 

It's not very clear but if you read the CI build for windows it fails in when it install the requirements because of `UnicodeEncodeError: 'charmap' codec can't encode character '\u2502' in position 2: character maps to <undefined>`

I can remove the message when I'm not installing `togax-xml-layout-plugin` as requirement (in the pyproject file). You can maybe check if there si not a weird character somewhere that could make it fail ?

**Comment by m1nuzz** [comment] 2024-02-19 13:32
> Наконец-то появилось время для этого...@k-aito, спасибо, что нашел это. Проблема заключалась в требованиях к макету togax-xml. У него была зависимость только для Linux (pygobject).
> 
> Итак, теперь MSI обновлен до последней версии. (Также здесь: [master-windows-2022.msi.zip](https://github.com/sinedie/SRTranslator/files/14331525/master-windows-2022.msi.zip) )
> 
> Закройте, если проблема решена.

![image](https://github.com/sinedie/SRTranslator/assets/109736024/2c20df85-bc9e-47ee-8e9a-db5c7c78ec5e)

I'm getting this error with this update
```
Traceback (most recent call last):
  File "\app_packages\togax_xml_layout\xml_parser.py", line 146, in parse_element
    instance = element_to_class(element.tag, attributes)
  File "\app_packages\togax_xml_layout\xml_parser.py", line 106, in element_to_class
    instance = klass(**init_args)
  File "\app_packages\toga\widgets\activityindicator.py", line 25, in __init__
    self._impl = self.factory.ActivityIndicator(interface=self)
  File "\app_packages\toga_winforms\factory.py", line 76, in __getattr__
    raise NotImplementedError(f"Toga's Winforms backend doesn't implement {name}")
NotImplementedError: Toga's Winforms backend doesn't implement ActivityIndicator

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\app\srtranslatorGUI\__main__.py", line 4, in <module>
    main().main_loop()
  File "\app_packages\toga\app.py", line 749, in main_loop
    self._impl.main_loop()
  File "\app_packages\toga_winforms\app.py", line 284, in main_loop
    raise self._exception
  File "\app_packages\toga_winforms\app.py", line 257, in run_app
    self.create()
  File "\app_packages\toga_winforms\app.py", line 113, in create
    self.interface._startup()
  File "\app_packages\toga\app.py", line 710, in _startup
    self.startup()
  File "\app\srtranslatorGUI\app.py", line 50, in startup
    self.main_window = parse_layout(self, f.read())
  File "\app_packages\togax_xml_layout\xml_parser.py", line 158, in parse_layout
    return parse_element(app, tree)
  File "\app_packages\togax_xml_layout\xml_parser.py", line 131, in parse_element
    children.append(parse_element(app, child))
  File "\app_packages\togax_xml_layout\xml_parser.py", line 131, in parse_element
    children.append(parse_element(app, child))
  File "\app_packages\togax_xml_layout\xml_parser.py", line 131, in parse_element
    children.append(parse_element(app, child))
  [Previous line repeated 1 more time]
  File "\app_packages\togax_xml_layout\xml_parser.py", line 151, in parse_element
    instance = element_to_class(element.tag, attributes)
  File "\app_packages\togax_xml_layout\xml_parser.py", line 106, in element_to_class
    instance = klass(**init_args)
  File "\app_packages\toga\widgets\activityindicator.py", line 25, in __init__
    self._impl = self.factory.ActivityIndicator(interface=self)
  File "\app_packages\toga_winforms\factory.py", line 76, in __getattr__
    raise NotImplementedError(f"Toga's Winforms backend doesn't implement {name}")
NotImplementedError: Toga's Winforms backend doesn't implement ActivityIndicator
```

**Comment by k-aito** [comment] 2024-02-19 13:35
> Finally got time for this... @k-aito , ty for finding that. The issue was on togax-xml-layout requirements. It had a linux-only dependency (pygobject).
> 
> So, now the msi is updated on last relase. (Also here: [master-windows-2022.msi.zip](https://github.com/sinedie/SRTranslator/files/14331525/master-windows-2022.msi.zip))
> 
> Close if issue is solved.

Perfect, I had tried some random stuff when forking but I got nowhere close ^^



> > Наконец-то появилось время для этого...@k-aito, спасибо, что нашел это. Проблема заключалась в требованиях к макету togax-xml. У него была зависимость только для Linux (pygobject).
> > Итак, теперь MSI обновлен до последней версии. (Также здесь: [master-windows-2022.msi.zip](https://github.com/sinedie/SRTranslator/files/14331525/master-windows-2022.msi.zip) )
> > Закройте, если проблема решена.
> 
> ![image](https://private-user-images.githubusercontent.com/109736024/305964686-2c20df85-bc9e-47ee-8e9a-db5c7c78ec5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNDk5MzksIm5iZiI6MTcwODM0OTYzOSwicGF0aCI6Ii8xMDk3MzYwMjQvMzA1OTY0Njg2LTJjMjBkZjg1LWJjOWUtNDdlZS04ZTlhLWRiNWM3Yzc4ZWM1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQxMzMzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTU4YjFlNGQ5YjEyMTdmMTQwNzA2MjNiMDNlOWFkYWZkOThkYzQwOTIxYTYzYzM0ODk5YTJmYzEzY2E3YzAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M7y-0ywQkTx0UkMAUi8_04Ezj8GvBUUBnCtudGew6GQ)
> 
> I have this error with your update
> 
> ```
> Traceback (most recent call last):
>   File "\app_packages\togax_xml_layout\xml_parser.py", line 146, in parse_element
>     instance = element_to_class(element.tag, attributes)
>   File "\app_packages\togax_xml_layout\xml_parser.py", line 106, in element_to_class
>     instance = klass(**init_args)
>   File "\app_packages\toga\widgets\activityindicator.py", line 25, in __init__
>     self._impl = self.factory.ActivityIndicator(interface=self)
>   File "\app_packages\toga_winforms\factory.py", line 76, in __getattr__
>     raise NotImplementedError(f"Toga's Winforms backend doesn't implement {name}")
> NotImplementedError: Toga's Winforms backend doesn't implement ActivityIndicator
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "\app\srtranslatorGUI\__main__.py", line 4, in <module>
>     main().main_loop()
>   File "\app_packages\toga\app.py", line 749, in main_loop
>     self._impl.main_loop()
>   File "\app_packages\toga_winforms\app.py", line 284, in main_loop
>     raise self._exception
>   File "\app_packages\toga_winforms\app.py", line 257, in run_app
>     self.create()
>   File "\app_packages\toga_winforms\app.py", line 113, in create
>     self.interface._startup()
>   File "\app_packages\toga\app.py", line 710, in _startup
>     self.startup()
>   File "\app\srtranslatorGUI\app.py", line 50, in startup
>     self.main_window = parse_layout(self, f.read())
>   File "\app_packages\togax_xml_layout\xml_parser.py", line 158, in parse_layout
>     return parse_element(app, tree)
>   File "\app_packages\togax_xml_layout\xml_parser.py", line 131, in parse_element
>     children.append(parse_element(app, child))
>   File "\app_packages\togax_xml_layout\xml_parser.py", line 131, in parse_element
>     children.append(parse_element(app, child))
>   File "\app_packages\togax_xml_layout\xml_parser.py", line 131, in parse_element
>     children.append(parse_element(app, child))
>   [Previous line repeated 1 more time]
>   File "\app_packages\togax_xml_layout\xml_parser.py", line 151, in parse_element
>     instance = element_to_class(element.tag, attributes)
>   File "\app_packages\togax_xml_layout\xml_parser.py", line 106, in element_to_class
>     instance = klass(**init_args)
>   File "\app_packages\toga\widgets\activityindicator.py", line 25, in __init__
>     self._impl = self.factory.ActivityIndicator(interface=self)
>   File "\app_packages\toga_winforms\factory.py", line 76, in __getattr__
>     raise NotImplementedError(f"Toga's Winforms backend doesn't implement {name}")
> NotImplementedError: Toga's Winforms backend doesn't implement ActivityIndicator
> ```

That looks like an error for @sinedie because Toga doesn't implement something for Windows. Good luck @sinedie  ^^

**Comment by sinedie** [comment] 2024-02-19 13:43
@m1nuzz  New release [here](https://github.com/sinedie/SRTranslator/releases/tag/v0.3.7) got the updated msi.

**Comment by h4rdkor1** [comment] 2024-02-19 14:41
@sinedie @k-aito , Now the application opens but it freezes when try to translate subs.

![image](https://github.com/sinedie/SRTranslator/assets/21197676/a68b81d2-ca24-45dd-88fd-b428f97fbaa3)

**Comment by m1nuzz** [comment] 2024-02-19 18:41
> @sinedie @k-aito , Now the application opens but it freezes when try to translate subs.
> 
> ![image](https://private-user-images.githubusercontent.com/21197676/305986494-a68b81d2-ca24-45dd-88fd-b428f97fbaa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNjgzOTksIm5iZiI6MTcwODM2ODA5OSwicGF0aCI6Ii8yMTE5NzY3Ni8zMDU5ODY0OTQtYTY4YjgxZDItY2EyNC00NWRkLTg4ZmQtYjQyOGY5N2ZiYWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDE4NDEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4YzgzNDFiMTIwYjUyNzA0MTQyOGQzZDZmYjUwODEwOWZlYzQwMzAyZWFjN2ZjMmExNTBiYWI4MDMwY2I5ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DOxmLfG2zBY5eufkG-dOvUO3KvcIUqHLOie2dag2q1o)

same

**Comment by dante3732** [comment] 2024-02-24 14:59
> @sinedie @k-aito , Now the application opens but it freezes when try to translate subs.
> 
> ![image](https://private-user-images.githubusercontent.com/21197676/305986494-a68b81d2-ca24-45dd-88fd-b428f97fbaa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3ODcwNjIsIm5iZiI6MTcwODc4Njc2MiwicGF0aCI6Ii8yMTE5NzY3Ni8zMDU5ODY0OTQtYTY4YjgxZDItY2EyNC00NWRkLTg4ZmQtYjQyOGY5N2ZiYWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDE0NTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1Y2ViODRmN2NiOWIzYjBjZDRmNGIzYWM5OGZiY2NlMzVmMjY2MTg3MGU4ZTgxYmVkZDZmYmQxMDNjZjkwMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WZXYBtnhbWZpyFWbad0zdX2MXp43oIO-9N3HsPGx-R4)

Same

**Comment by k-aito** [comment] 2024-02-24 22:26
Hello  @h4rdkor1 @m1nuzz @dante3732 

I give a try with 1 SRT (using choose file) and pydeeplx, and it works for me on Linux. Can one of you give it a try with something else than DeepL scraper?

**Comment by dante3732** [comment] 2024-02-25 15:45
> Hello @h4rdkor1 @m1nuzz @dante3732
> 
> I give a try with 1 SRT (using choose file) and pydeeplx, and it works for me on Linux. Can one of you give it a try with something else than DeepL scraper?

It happened on any translator with WIN 11.

**Comment by k-aito** [comment] 2024-02-25 15:46
Hello @dante3732 

There is no debug information in the terminal? Maybe launching the exe from the terminal would display something as logs.

**Comment by k-aito** [comment] 2024-02-25 15:48
@dante3732 it's possible that you give a try with a very small SRT, like 1 sentence. Just to be sure that it is really blocking and not just missing to display the progression.

**Comment by dante3732** [comment] 2024-02-25 15:54
> it's possible that you give a try with a very small SRT, like 1 sentence. Just to be sure that it is really blocking and not just missing to display the progression.

Immediately after clicking translate, the program stops responding. I tried SRT with a single line.

> Hello @dante3732
> 
> There is no debug information in the terminal? Maybe launching the exe from the terminal would display something as logs.

I do not know how to do this through the terminal.

**Comment by k-aito** [comment] 2024-02-25 16:25
Hello @dante3732 

Can you give a try to this one, I added asyncio as dependance.

[k-aito-patch-1-windows-2022.msi.zip](https://github.com/sinedie/SRTranslator/files/14396975/k-aito-patch-1-windows-2022.msi.zip)

**Comment by dante3732** [comment] 2024-02-25 16:28
> Can you give a try to this one, I added asyncio as dependance.

Same stops responding.

**Comment by k-aito** [comment] 2024-02-25 17:04
@dante3732 for launching the file from the terminal you can open a command prompt and then drag and drop the executable, maybe there will be some information.

You can start a command prompt by doing  `execute` and typing `cmd` if I recall correctly.

**Comment by dante3732** [comment] 2024-02-25 21:44
> for launching the file from the terminal you can open a command prompt and then drag and drop the executable, maybe there will be some information.

When running this way, no debugging appears on the command line.

**Comment by dante3732** [comment] 2024-02-26 10:39
> no big change, I just removed the display of the progression, can you try again the 1 line SRT to see if it can finish?

Same stop respond.

**Comment by arlovibre** [comment] 2024-03-02 06:46
> [k-aito-patch-1-windows-2022.msi.zip](https://github.com/sinedie/SRTranslator/files/14398380/k-aito-patch-1-windows-2022.msi.zip)
> 
> @dante3732 no big change, I just removed the display of the progression, can you try again the 1 line SRT to see if it can finish?
> 
> The idea is to try to find what part of the application is freezing windows.

It freezes again unfortunately. Have you had any chance to look into it again?

**Comment by k-aito** [comment] 2024-03-03 17:03
Hello @arlovibre 

On my side without a Windows it's very difficult. For me, the command line version is working, and I don't see any reason it would hang with the GUI code that works on Linux.

Until someone that can try to build and run the briefcase version and maybe have some debug info, I think it will be difficult to fix.

**Comment by k-aito** [comment] 2024-03-06 11:32
Hello @arlovibre @dante3732 @m1nuzz 

I read the code again and the only thing that for me must be an issue is the async function.
So I added prints and I hope that when it freezes it will show the last that worked to be certain that the error is from there.

[k-aito-patch-1-windows-2022.msi(2).zip](https://github.com/sinedie/SRTranslator/files/14509140/k-aito-patch-1-windows-2022.msi.2.zip)

**Comment by dante3732** [comment] 2024-03-06 11:47
> Hello @arlovibre @dante3732 @m1nuzz
> 
> I read the code again and the only thing that for me must be an issue is the async function. So I added prints and I hope that when it freezes it will show the last that worked to be certain that the error is from there.
> 
> [k-aito-patch-1-windows-2022.msi(2).zip](https://github.com/sinedie/SRTranslator/files/14509140/k-aito-patch-1-windows-2022.msi.2.zip)

It freezes as before.

**Comment by k-aito** [comment] 2024-03-06 12:20
Hello @dante3732 there are no numbers at all that are displayed at the right of the screen?

![image](https://github.com/sinedie/SRTranslator/assets/77667659/f8ab1b23-39c5-4a57-abc5-1133a8de0ea0)

**Comment by dante3732** [comment] 2024-03-06 13:09
> Hello @dante3732 there are no numbers at all that are displayed at the right of the screen?
> 
> ![image](https://private-user-images.githubusercontent.com/77667659/310494291-f8ab1b23-39c5-4a57-abc5-1133a8de0ea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzA4MDgsIm5iZiI6MTcwOTczMDUwOCwicGF0aCI6Ii83NzY2NzY1OS8zMTA0OTQyOTEtZjhhYjFiMjMtMzljNS00YTU3LWFiYzUtMTEzM2E4ZGUwZWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEzMDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZjczODAzYzA1ZDQ2ZGQ3ZGMwMWI0MjEyZjFjN2MwOThhYzFiMjBmZjFhMGU2Y2VhYWZlODM0NGVhMWFiNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z_Imwfy967-cLUhrHWAQ0KmdiCC-9WnA4mJbVSESTDc)

![image](https://github.com/sinedie/SRTranslator/assets/66036249/c176264c-2875-454f-9aa5-a65ae7633a11)

**Comment by k-aito** [comment] 2024-03-06 13:18
It means that the function is not even launched... Maybe it's related to the toga xml layout. I will try to see if I find something about it.

@sinedie if you have an idea what could prevent windows to launch the function don't hesitate

**Comment by sinedie** [comment] 2024-03-06 20:05
Not having windows to debug is the main problem for me.

I don't think it is related with toma-xml-layout as if it didn't work app wouldn't open in first place.

Most probably it is an AsyncIO issue, maybe it is blocking the main Toga thread. Idk.

Gonna check if can get a virtual windows machine or anything and try to fix it. Dont have too many spare time lately, but will fix this for sure.

**Comment by sinedie** [comment] 2024-03-21 13:44
@k-aito I can confirm the issue is with AsynIO blocking the main event loop of Toga. The issue happened to me when, inside translate function, I use any other subrutine, even with only a print statement. Still researching but right now Im lost on how to solve it.

Im seriusly thinking in switch to another GUI framework. Even with another tech stack like Tauri or NeutralinoJs

**Comment by k-aito** [comment] 2024-03-21 14:02
Hello @sinedie 

Only on Windows or on Linux also? I didn't let it completely translate something on Linux, but I didn't notice it was blocking.

I don't know Tauri or Nautralinojs at all but could still be fun to look at it.

**Comment by sinedie** [comment] 2024-03-21 14:04
@k-aito in windows, linux works fine

**Comment by k-aito** [comment] 2024-03-21 14:11
It would not work to just launch the translation in a thread instead of using an async function?

I even think the issue is more windows related than asyncio on his own. Because it works on Linux I guess it's a process issue that is only on Windows but that sounds really difficult to debug...

**Comment by jaum20** [comment] 2024-04-22 19:10
Any updates on the freeze problem?

**Comment by sinedie** [comment] 2024-07-16 13:46
@jaum20, I'll be back to this issue this week. I took too many time. I think I'll use another framework for the GUI as briefcase didn't work as planned

**Comment by sinedie** [comment] 2024-10-17 01:53
Finally I manage to work in this. I decided to start over with another python/flutter framework called Flet. It is functional in both linux and windows. There is a new version 0.3.9 to support something in the new UI. You can find it in the master branch.

Currently I'm working in a github action to generate the executables but if you wanna test it you could go to the folder GUI, install the requirements and run flet app:

```
cd ./GUI
pip install -r ./requirements.txt
flet run main.py
```

And if you want to pack it yourself, `run flet pack main.py` or `flet build main.py`. (Check the [flet](https://flet.dev/) documentation it is pretty simple)

There will be issues as it is work in progress but it is better than the other GUI. App size is one of them but I think there is no workaround for that. Also, by now you can queue multiple srt files at the same time but it will only translate one at the time

Ty for waiting and using this, hope you like it. Also, I'm open to recieve feedback.

**Comment by sinedie** [comment] 2024-10-18 01:35
- Windows test
Opens some weird terminals for background process -will see if I can avoid that later-
![image](https://github.com/user-attachments/assets/4d1b775c-35e4-4878-870d-effe54fad870)
- Linux test
The artifact should work. I got an issue but it was a conflict with my version of a dependency, right now I don't wanna mess my system, so will check later. Works if you package yourself. Just go to GUI, and run `flet pack main.py`

Artifacts will be in the github actions tab. You can find them here too:
Windows build: https://github.com/sinedie/SRTranslator/actions/runs/11395632789/artifacts/2071991302
Linux build: https://github.com/sinedie/SRTranslator/actions/runs/11395632805/artifacts/2071985687

**Closed by sinedie** 2024-10-18 01:35 UTC
