### ISSUE TITLE
GUI version does not work

### ISSUE THREAD

**Issue by unleashed7** [sinedie/SRTranslator#86] opened 2024-03-25 09:40 UTC
Tried different srt files, different translators (DeepL API and DeepL Scraper), but it just freezes and stops responding indefinitely.

Are there any logs to figure out what's happening?

**Comment by sinedie** [comment] 2024-04-01 11:44
On windows, linux?

**Comment by bw4518** [comment] 2024-04-01 20:50
Windows 10 here, same problem.

**Comment by unleashed7** [comment] 2024-04-04 08:50
> On windows, linux?

Windows version, yes!

The non GUI build worked without a problem.

**Comment by sinedie** [comment] 2024-04-04 16:31
duplicate of #85, working in a solution in my spare time (too little lately)

**Closed by sinedie** 2024-04-04 16:31 UTC
